databases:
  - name: cybersec_cert_tracker
    databaseName: cybersec_cert_tracker
    user: cybersec_cert_tracker

services:
  - type: web
    name: cybersec_cert_tracker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cybersec_cert_tracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false